version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: maple-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      # .env 파일에서 값을 읽어옵니다
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_SCHEMA_NAME}
      TZ: ${TZ}
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data: