# Issue #143: Loki Datasource Configuration
# Grafana가 시작될 때 자동으로 Loki 데이터소스를 등록합니다.

apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki  # PR #206: 대시보드 참조용 UID 추가
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: false
